name: lingsix
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.9.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  noise_meter: ^5.1.0
  audioplayers: ^6.1.0
  volume_controller: ^3.4.1
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  google_sign_in: ^6.3.0
  email_validator: ^3.0.0
  http: ^1.2.0
  google_fonts: ^8.0.2
  sign_in_button: ^3.2.0
  shared_preferences: ^2.1.1 
  rename_app: ^1.6.5
  fl_chart: ^1.1.1
  csv: ^8.0.0
  path_provider: ^2.1.2
  share_plus: ^12.0.1
  provider: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/common/logo/app_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/common/bg/
    - assets/common/illustrations/
    - assets/common/illustrations/home/
    - assets/common/logo/
    - assets/common/sounds/
    - assets/themes/default/bg/
    - assets/themes/default/characters/cat/
    - assets/themes/default/characters/dino/
    - assets/themes/default/characters/rabbit/
    - assets/themes/summer/bg/
    - assets/themes/summer/characters/cat/
    - assets/themes/summer/characters/dino/
    - assets/themes/summer/characters/rabbit/
    - assets/data/vocabulary.json
    - assets/content/vocabulary/ah/ban/
    - assets/content/vocabulary/ah/chan/
    - assets/content/vocabulary/ah/fa/
    - assets/content/vocabulary/ah/khao/
    - assets/content/vocabulary/ah/ma/
    - assets/content/vocabulary/ah/pa/
    - assets/content/vocabulary/ah/pak/
    - assets/content/vocabulary/ah/pla/
    - assets/content/vocabulary/ah/ta/
    - assets/content/vocabulary/ah/ya/
    - assets/content/vocabulary/ah/ya2/
    - assets/content/vocabulary/ee/chi/
    - assets/content/vocabulary/ee/di/
    - assets/content/vocabulary/ee/khi/
    - assets/content/vocabulary/ee/mhee/
    - assets/content/vocabulary/ee/mit/
    - assets/content/vocabulary/ee/ni/
    - assets/content/vocabulary/ee/phi/
    - assets/content/vocabulary/ee/pi/
    - assets/content/vocabulary/ee/si/
    - assets/content/vocabulary/ee/ti/
    - assets/content/vocabulary/m/mae/
    - assets/content/vocabulary/m/maeo/
    - assets/content/vocabulary/m/mai/
    - assets/content/vocabulary/m/mamuang/
    - assets/content/vocabulary/m/mek/
    - assets/content/vocabulary/m/mo/
    - assets/content/vocabulary/m/mon/
    - assets/content/vocabulary/m/muak/
    - assets/content/vocabulary/m/mue/
    - assets/content/vocabulary/m/muek/
    - assets/content/vocabulary/s/sabu/
    - assets/content/vocabulary/s/saeng/
    - assets/content/vocabulary/s/sai/
    - assets/content/vocabulary/s/si/
    - assets/content/vocabulary/s/siang/
    - assets/content/vocabulary/s/so/
    - assets/content/vocabulary/s/som/
    - assets/content/vocabulary/s/soup/
    - assets/content/vocabulary/s/suea/
    - assets/content/vocabulary/s/suea2/
    - assets/content/vocabulary/sh/cha/
    - assets/content/vocabulary/sh/chai/
    - assets/content/vocabulary/sh/chao/
    - assets/content/vocabulary/sh/cheese/
    - assets/content/vocabulary/sh/chingcha/
    - assets/content/vocabulary/sh/chiwit/
    - assets/content/vocabulary/sh/chon/
    - assets/content/vocabulary/sh/chop/
    - assets/content/vocabulary/sh/chue/
    - assets/content/vocabulary/sh/chut/
    - assets/content/vocabulary/oo/chung/
    - assets/content/vocabulary/oo/du/
    - assets/content/vocabulary/oo/hu/
    - assets/content/vocabulary/oo/khu/
    - assets/content/vocabulary/oo/mu/
    - assets/content/vocabulary/oo/ngu/
    - assets/content/vocabulary/oo/nu/
    - assets/content/vocabulary/oo/phukhao/
    - assets/content/vocabulary/oo/pu/
    - assets/content/vocabulary/oo/tu/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
